name: runner
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # routing
  go_router:
    ^10.0.0

  # UI
  cupertino_icons: ^1.0.2
  flutter_tabler_icons: ^1.2.0
  flutter_svg: ^2.0.7

  # BloC
  flutter_bloc: 8.1.3
  bloc_concurrency: 0.2.2

  # Storage
  shared_preferences: 2.2.0

    # Dev
  l: 4.0.2
  logger: ^2.0.0
  equatable: ^2.0.5
  animated_toggle_switch: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
    ^2.0.0

    # Code generation
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  json_serializable: 6.7.1
  build_runner: 2.4.6
  freezed: 2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
